- name: start monitor service
  hosts: all

  tasks:
    - name: mkdir
      file:
        path: "./.service/monitor_service"
        state: directory
        mode: 0777
        recurse: yes

    - name: git clone
      git:
        repo: "https://github.com/amanakin/monitor_script.git"
        dest: "./.service/monitor_service"
        version: master
        clone: yes
        update: yes
        force: yes

    - name: run service
      ansible.builtin.shell:
        cmd: chmod +rx ./.service/monitor_service/monitor.sh & ./.service/monitor_service/monitor.sh START
